#! /bin/bash

osc() {
    echo -ne "\\e]$1\\a"
}
osc  '4;0;#000000'  # black
osc  '4;1;#401401'  # red
osc  '4;2;#481d02'  # green
osc  '4;3;#501e03'  # brown
osc  '4;4;#581f04'  # blue
osc  '4;5;#602005'  # magenta
osc  '4;6;#682406'  # cyan
osc  '4;7;#702807'  # grey
osc  '4;8;#782d02'  # dark grey
osc  '4;9;#803008'  # red
osc '4;10;#884A09' # green
osc '4;11;#99550A' # yellow
osc '4;12;#AA5A0B' # blue
osc '4;13;#DD660C' # magenta
osc '4;14;#EE770D' # cyan
osc '4;15;#FF8808' # white
osc   '10;#FFAA00'   # foreground
osc   '11;#000000'   # background

