#! /bin/bash

osc() {
    echo -ne "\\e]$1\\a"
}
osc  '4;0;#000000'  # black
osc  '4;1;#015001'  # red
osc  '4;2;#125802'  # green
osc  '4;3;#186003'  # brown
osc  '4;4;#226804'  # blue
osc  '4;5;#287005'  # magenta
osc  '4;6;#337806'  # cyan
osc  '4;7;#447F04'  # grey
osc  '4;8;#0A1702'  # dark grey
osc  '4;9;#448808'  # red
osc '4;10;#4A9909' # green
osc '4;11;#55AA0A' # yellow
osc '4;12;#5ABB0B' # blue
osc '4;13;#66CC0C' # magenta
osc '4;14;#77DD0D' # cyan
osc '4;15;#88FF08' # white
osc   '10;#AAFF00'   # foreground
osc   '11;#000000'   # background

