#! /bin/bash

osc() {
    echo -ne "\\e]$1\\a"
}
osc '4;0;#000000'  # black
osc '4;1;#484848'  # red
osc '4;2;#505050'  # green
osc '4;3;#585858'  # brown
osc '4;4;#606060'  # blue
osc '4;5;#686868'  # magenta
osc '4;6;#707070'  # cyan
osc '4;7;#777777'  # grey
osc '4;8;#171717'  # dark grey
osc '4;9;#888888'  # red
osc '4;10;#999999' # green
osc '4;11;#AAAAAA' # yellow
osc '4;12;#BBBBBB' # blue
osc '4;13;#CCCCCC' # magenta
osc '4;14;#DDDDDD' # cyan
osc '4;15;#FFFFFF' # white

osc '10;#DDDDDD'   # foreground
osc '11;#000000'   # background

