#! /bin/bash

osc() {
    echo -ne "\\e]$1\\a"
}
osc '4;0;#202020'  # black
osc '4;1;#AA0000'  # red
osc '4;2;#00AA00'  # green
osc '4;3;#AA5500'  # brown
osc '4;4;#0000AA'  # blue
osc '4;5;#AA00AA'  # magenta
osc '4;6;#00AAAA'  # cyan
osc '4;7;#AAAAAA'  # grey
osc '4;8;#555555'  # dark grey
osc '4;9;#FF5555'  # red
osc '4;10;#55FF55' # green
osc '4;11;#FFFF55' # yellow
osc '4;12;#5555FF' # blue
osc '4;13;#FF55FF' # magenta
osc '4;14;#55FFFF' # cyan
osc '4;15;#FFFFFF' # white

osc '10;#DDDDDD'   # foreground
osc '11;#000000'   # background

